name: modules
description: A OpenIoTHub Flutter modules package.
version: 0.0.1
author: Farry
homepage: https://github.com/OpenIoTHub

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  openiothub_grpc_api:
    git: https://github.com/OpenIoTHub/openiothub-grpc-api
  server_grpc_api:
    git: https://github.com/OpenIoTHub/server-grpc-api
  gateway_grpc_api:
    git: https://github.com/OpenIoTHub/gateway-grpc-api
  #  grpc
  grpc: ^1.0.2
  #  grpc协议
  protobuf: ^1.0.1
  #  颜色选择器
  flutter_colorpicker: ^0.3.2
  #  webDAV的文件浏览器
  webdav:
    git: https://github.com/OpenIoTHub/dart-webdav
  #  app内嵌网页浏览器
  webview_flutter: ^0.3.19+9
  #  打开url
  url_launcher: ^5.0.2
  #  数据存储
  shared_preferences: ^0.5.7+2
  #  事件总线
  event_bus: ^1.1.0
  #  配网start
  #  esp配网
  smartconfig: ^0.0.1
  #  w60x的OneShot配网
  flutter_oneshot:
    git: https://github.com/iotdevice/flutter_oneshot
  # 庆科easylink
  flutter_easylink:
    git: https://github.com/iotdevice/flutter_easylink
  ## 汉枫smartlink
  flutter_smartlink:
    git: https://github.com/iotdevice/flutter_smartlink
  # AirKiss
  airkiss: ^1.0.1
  #  获取wifi名和bssid
  connectivity: ^0.4.8+2
  #  动态请求权限，定位，存储等
  permission_handler: ^3.1.0
  #  配网end
  multicast_dns: ^0.2.2
  #  mdns_plugin: ^1.1.4
  package_info: ^0.4.0+3
  uuid: ^2.1.0
  #ssh file
#  file_picker: ^1.3.4+1
#  flutter_speed_dial: ^1.1.1
#  floating_action_row: ^0.1.0
#  md2_tab_indicator: ^1.0.2
#  open_file: ^2.0.1+2
#  outline_material_icons: ^0.1.0
  path_provider: ^1.2.0
#  provider: ^2.0.0
#  ssh: ^0.0.3
  #ssh file over

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
